services:
  flaresolverr:
    image: crpi-qp8hiqijfnilf93t.cn-hangzhou.personal.cr.aliyuncs.com/bulexu/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Asia/Shanghai
    ports:
      - '8191:8191'
    restart: unless-stopped

  newsnow:
    image: crpi-qp8hiqijfnilf93t.cn-hangzhou.personal.cr.aliyuncs.com/bulexu/newsnow:latest
    container_name: newsnow
    depends_on:
      - flaresolverr
    ports:
      - '4444:4444'
    volumes:
      - newsnow_data:/usr/app/.data
      # 挂载时区配置
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    environment:
      - TZ=Asia/Shanghai
      - HOST=0.0.0.0
      - PORT=4444
      - NODE_ENV=production
      - G_CLIENT_ID=
      - G_CLIENT_SECRET=
      - JWT_SECRET=
      - INIT_TABLE=true
      - ENABLE_CACHE=true
      - PRODUCTHUNT_API_TOKEN=
      - FLARESOLVERR_URL=http://flaresolverr:8191

volumes:
  newsnow_data:
    name: newsnow_data
