services:
  # cloakbrowser:
  #   image: cloakhq/cloakbrowser:latest
  #   container_name: cloakbrowser
  #   command: cloakserve
  #   environment:
  #     - TZ=Asia/Shanghai
  #     - CLOAKBROWSER_AUTO_UPDATE=false
  #   ports:
  #     - '9222:9222'
  #   restart: unless-stopped

  newsnow:
    image: crpi-qp8hiqijfnilf93t.cn-hangzhou.personal.cr.aliyuncs.com/bulexu/newsnow:v2.0.4
    container_name: newsnow
    # depends_on:
    #   - cloakbrowser
    ports:
      - '4444:4444'
    volumes:
      - newsnow_data:/usr/app/.data
      # 挂载时区配置
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    environment:
      - TZ=Asia/Shanghai
      - HOST=0.0.0.0
      - PORT=4444
      - NODE_ENV=production
      - G_CLIENT_ID=
      - G_CLIENT_SECRET=
      - JWT_SECRET=
      - INIT_TABLE=true
      - ENABLE_CACHE=true
      - PRODUCTHUNT_API_TOKEN=
      - CLOAKBROWSER_CDP_URL=http://cloakbrowser:9222

volumes:
  newsnow_data:
    name: newsnow_data
