services:
  flaresolverr:
    image: crpi-qp8hiqijfnilf93t.cn-hangzhou.personal.cr.aliyuncs.com/bulexu/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
    ports:
      - '8191:8191'
    restart: unless-stopped

  newsnow:
    build: .
    depends_on:
      - flaresolverr
    ports:
      - '4444:4444'
    volumes:
      - newsnow_data:/usr/app/.data
    environment:
      - G_CLIENT_ID=
      - G_CLIENT_SECRET=
      - JWT_SECRET=
      - INIT_TABLE=true
      - ENABLE_CACHE=true
      - FLARESOLVERR_URL=http://flaresolverr:8191

volumes:
  newsnow_data:
    name: newsnow_data
