import process from "node:process"
import { Interval } from "./consts"
import { typeSafeObjectFromEntries } from "./type.util"
import type { OriginSource, Source, SourceID } from "./types"

export const Time = {
  Test: 1,
  Realtime: 2 * 60 * 1000,
  Fast: 5 * 60 * 1000,
  Default: Interval, // 10min
  Common: 30 * 60 * 1000,
  Slow: 60 * 60 * 1000,
}

export const originSources = {
  // "v2ex": {
  //   name: "V2EX",
  //   color: "slate",
  //   home: "https://v2ex.com/",
  //   sub: {
  //     share: {
  //       title: "最新分享",
  //       column: "tech",
  //     },
  //   },
  // },
  "zhihu": {
    name: "知乎",
    type: "hottest",
    column: "china",
    color: "blue",
    home: "https://www.zhihu.com",
  },
  "weibo": {
    name: "微博",
    title: "实时热搜",
    type: "hottest",
    column: "china",
    color: "red",
    interval: Time.Realtime,
    home: "https://weibo.com",
  },
  // "zaobao": {
  //   name: "联合早报",
  //   interval: Time.Common,
  //   type: "realtime",
  //   column: "world",
  //   color: "red",
  //   desc: "来自第三方网站: 早晨报",
  //   home: "https://www.zaobao.com",
  // },
  // "coolapk": {
  //   name: "酷安",
  //   type: "hottest",
  //   column: "tech",
  //   color: "green",
  //   title: "今日最热",
  //   home: "https://coolapk.com",
  // },
  // "mktnews": {
  //   name: "MKTNews",
  //   column: "finance",
  //   home: "https://mktnews.net",
  //   color: "indigo",
  //   interval: Time.Realtime,
  //   sub: {
  //     flash: {
  //       title: "快讯",
  //     },
  //   },
  // },
  "wallstreetcn": {
    name: "华尔街见闻",
    color: "blue",
    column: "finance",
    home: "https://wallstreetcn.com/",
    sub: {
      quick: {
        type: "realtime",
        interval: Time.Fast,
        title: "快讯",
      },
      news: {
        title: "最新",
        interval: Time.Common,
      },
      hot: {
        title: "最热",
        type: "hottest",
        interval: Time.Common,
      },
    },
  },
  "36kr": {
    name: "36氪",
    type: "realtime",
    color: "blue",
    home: "https://36kr.com",
    column: "tech",
    disable: "cf",
    sub: {
      quick: {
        title: "快讯",
      },
      // renqi: {
      //   type: "hottest",
      //   title: "人气榜",
      // },
    },
  },
  "douyin": {
    name: "抖音",
    type: "hottest",
    column: "china",
    color: "gray",
    home: "https://www.douyin.com",
  },
  "hupu": {
    name: "虎扑",
    home: "https://hupu.com",
    column: "sports",
    title: "主干道热帖",
    type: "hottest",
    color: "red",
  },
  "dongqiudi": {
    name: "懂球帝",
    title: "头条",
    type: "realtime",
    column: "sports",
    color: "green",
    home: "https://www.dongqiudi.com",
  },
  "aihot": {
    name: "AIHOT",
    type: "realtime",
    column: "tech",
    color: "blue",
    interval: Time.Fast,
    home: "https://aihot.virxact.com/all",
  },
  "qbitai": {
    name: "量子位",
    column: "tech",
    color: "blue",
    detail: true,
    home: "https://www.qbitai.com/",
    sub: {
      zx: {
        title: "资讯",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.qbitai.com/category/%e8%b5%84%e8%ae%af",
      },
    },
  },
  "tieba": {
    name: "百度贴吧",
    title: "热议",
    column: "china",
    type: "hottest",
    color: "blue",
    home: "https://tieba.baidu.com",
  },
  "toutiao": {
    name: "今日头条",
    type: "hottest",
    column: "china",
    color: "red",
    home: "https://www.toutiao.com",
  },
  // "ithome": {
  //   name: "IT之家",
  //   color: "red",
  //   column: "tech",
  //   type: "realtime",
  //   home: "https://www.ithome.com",
  // },
  "thepaper": {
    name: "澎湃新闻",
    interval: Time.Common,
    type: "hottest",
    column: "china",
    title: "热榜",
    color: "gray",
    home: "https://www.thepaper.cn",
  },
  "sputniknewscn": {
    name: "卫星通讯社",
    color: "orange",
    column: "world",
    home: "https://sputniknews.cn",
  },
  "cankaoxiaoxi": {
    name: "参考消息",
    color: "red",
    column: "world",
    interval: Time.Common,
    home: "https://china.cankaoxiaoxi.com",
  },
  // "pcbeta": {
  //   name: "远景论坛",
  //   color: "blue",
  //   column: "tech",
  //   home: "https://bbs.pcbeta.com",
  //   sub: {
  //     windows11: {
  //       title: "Win11",
  //       type: "realtime",
  //       interval: Time.Fast,
  //     },
  //     windows: {
  //       title: "Windows 资源",
  //       type: "realtime",
  //       interval: Time.Fast,
  //       disable: true,
  //     },
  //   },
  // },
  "cls": {
    name: "财联社",
    color: "red",
    column: "finance",
    home: "https://www.cls.cn",
    sub: {
      telegraph: {
        title: "电报",
        interval: Time.Fast,
        type: "realtime",
      },
      depth: {
        title: "深度",
      },
      hot: {
        title: "热门",
        type: "hottest",
      },
    },
  },
  "xueqiu": {
    name: "雪球",
    color: "blue",
    home: "https://xueqiu.com",
    column: "finance",
    sub: {
      hotstock: {
        title: "热门股票",
        interval: Time.Realtime,
        type: "hottest",
      },
    },
  },
  "gelonghui": {
    name: "格隆汇",
    color: "blue",
    title: "事件",
    column: "finance",
    type: "realtime",
    interval: Time.Realtime,
    home: "https://www.gelonghui.com",
  },
  // "fastbull": {
  //   name: "法布财经",
  //   color: "emerald",
  //   home: "https://www.fastbull.cn",
  //   column: "finance",
  //   sub: {
  //     express: {
  //       title: "快讯",
  //       type: "realtime",
  //       interval: Time.Realtime,
  //     },
  //     news: {
  //       title: "头条",
  //       interval: Time.Common,
  //     },
  //   },
  // },
  // "solidot": {
  //   name: "Solidot",
  //   color: "teal",
  //   column: "tech",
  //   home: "https://solidot.org",
  //   interval: Time.Slow,
  // },
  // "hackernews": {
  //   name: "Hacker News",
  //   color: "orange",
  //   column: "tech",
  //   type: "hottest",
  //   home: "https://news.ycombinator.com/",
  // },
  // "producthunt": {
  //   name: "Product Hunt",
  //   color: "red",
  //   column: "tech",
  //   type: "hottest",
  //   home: "https://www.producthunt.com/",
  // },
  "github": {
    name: "Github",
    color: "gray",
    home: "https://github.com/",
    column: "tech",
    sub: {
      "trending-today": {
        title: "Today",
        type: "hottest",
      },
    },
  },
  "bilibili": {
    name: "哔哩哔哩",
    color: "blue",
    home: "https://www.bilibili.com",
    sub: {
      "hot-search": {
        title: "热搜",
        column: "china",
        type: "hottest",
      },
      "hot-video": {
        title: "热门视频",
        disable: "cf",
        column: "china",
        type: "hottest",
      },
      "ranking": {
        title: "排行榜",
        column: "china",
        disable: "cf",
        type: "hottest",
        interval: Time.Common,
      },
    },
  },
  "kuaishou": {
    name: "快手",
    type: "hottest",
    column: "china",
    color: "orange",
    // cloudflare pages cannot access
    disable: "cf",
    home: "https://www.kuaishou.com",
  },
  "kaopu": {
    name: "靠谱新闻",
    column: "world",
    color: "gray",
    interval: Time.Common,
    desc: "不一定靠谱，多看多思考",
    home: "https://kaopu.news/",
  },
  "jin10": {
    name: "金十数据",
    column: "finance",
    color: "blue",
    type: "realtime",
    home: "https://www.jin10.com",
  },
  "baidu": {
    name: "百度热搜",
    column: "china",
    color: "blue",
    type: "hottest",
    home: "https://www.baidu.com",
  },
  "linuxdo": {
    name: "LINUX DO",
    column: "tech",
    color: "slate",
    home: "https://linux.do/",
    disable: true,
    sub: {
      latest: {
        title: "最新",
        home: "https://linux.do/latest",
      },
      hot: {
        title: "今日最热",
        type: "hottest",
        interval: Time.Common,
        home: "https://linux.do/hot",
      },
    },
  },
  // "ghxi": {
  //   name: "果核剥壳",
  //   column: "china",
  //   color: "yellow",
  //   home: "https://www.ghxi.com/",
  //   disable: true,
  // },
  // "smzdm": {
  //   name: "什么值得买",
  //   column: "china",
  //   color: "red",
  //   type: "hottest",
  //   home: "https://www.smzdm.com",
  //   disable: true,
  // },
  // "nowcoder": {
  //   name: "牛客",
  //   column: "china",
  //   color: "blue",
  //   type: "hottest",
  //   home: "https://www.nowcoder.com",
  // },
  "sspai": {
    name: "少数派",
    column: "tech",
    color: "red",
    type: "hottest",
    home: "https://sspai.com",
  },
  "juejin": {
    name: "稀土掘金",
    column: "tech",
    color: "blue",
    type: "hottest",
    home: "https://juejin.cn",
  },
  "ifeng": {
    name: "凤凰网",
    column: "china",
    color: "red",
    type: "hottest",
    title: "热点资讯",
    home: "https://www.ifeng.com",
  },
  // "chongbuluo": {
  //   name: "虫部落",
  //   column: "china",
  //   color: "green",
  //   home: "https://www.chongbuluo.com",
  //   sub: {
  //     latest: {
  //       title: "最新",
  //       interval: Time.Common,
  //       home: "https://www.chongbuluo.com/forum.php?mod=guide&view=newthread",
  //     },
  //     hot: {
  //       title: "最热",
  //       type: "hottest",
  //       interval: Time.Common,
  //       home: "https://www.chongbuluo.com/forum.php?mod=guide&view=hot",
  //     },
  //   },
  // },
  // "douban": {
  //   name: "豆瓣",
  //   column: "china",
  //   title: "热门电影",
  //   color: "green",
  //   type: "hottest",
  //   home: "https://www.douban.com",
  // },
  // "steam": {
  //   name: "Steam",
  //   column: "world",
  //   title: "在线人数",
  //   color: "blue",
  //   type: "hottest",
  //   home: "https://store.steampowered.com",
  // },
  "tencent": {
    name: "腾讯新闻",
    column: "china",
    color: "blue",
    home: "https://news.qq.com",
    sub: {
      hot: {
        title: "综合早报",
        type: "hottest",
        interval: Time.Common,
        home: "https://news.qq.com/tag/aEWqxLtdgmQ=",
      },
    },
  },
  "freebuf": {
    name: "Freebuf",
    column: "china",
    title: "网络安全",
    color: "green",
    type: "hottest",
    home: "https://www.freebuf.com/",
  },
  // "qqvideo": {
  //   name: "腾讯视频",
  //   column: "china",
  //   color: "blue",
  //   home: "https://v.qq.com/",
  //   sub: {
  //     "tv-hotsearch": {
  //       title: "热搜榜",
  //       type: "hottest",
  //       interval: Time.Common,
  //       home: "https://v.qq.com/channel/tv",

  //     },
  //   },
  // },
  // "iqiyi": {
  //   name: "爱奇艺",
  //   column: "china",
  //   color: "green",
  //   home: "https://www.iqiyi.com",
  //   sub: {
  //     "hot-ranklist": {
  //       title: "热播榜",
  //       type: "hottest",
  //       interval: Time.Common,
  //       home: "https://www.iqiyi.com",
  //     },
  //   },
  // },
  "biketo": {
    name: "美骑网",
    column: "cycle-track",
    color: "blue",
    detail: true,
    home: "https://www.biketo.com",
    sub: {
      "hotnews": {
        title: "热点快报",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.biketo.com/hotnews/",
      },
      "activities": {
        title: "骑行活动",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.biketo.com/activities/",
      },
      "cyclexpress": {
        title: "美骑快讯",
        type: "realtime",
        interval: Time.Fast,
        home: "http://www.biketo.com/cyclexpress/",
      },
      "road": {
        title: "公路车",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.biketo.com/road/",
      },
      "mtb": {
        title: "山地车",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.biketo.com/mtb/",
      },
      "city": {
        title: "城市车",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.biketo.com/city/",
      },
      "touringbike": {
        title: "旅行车",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.biketo.com/touringbike/",
      },
      "e-bike": {
        title: "电助力",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.biketo.com/e-bike/",
      },
      "racingnews": {
        title: "赛事新闻",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.biketo.com/racingnews/",
      },
      "knowledge": {
        title: "知识",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.biketo.com/knowledge/",
      },
      "business": {
        title: "行业动态",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.biketo.com/racing/",
      },
      "insight": {
        title: "美骑观察",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.biketo.com/insight/",
      },
      "enterprise": {
        title: "企业探秘",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.biketo.com/enterprise/",
      },
      "shop": {
        title: "精品车店",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.biketo.com/shop/",
      },
      "interview": {
        title: "人物访谈",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.biketo.com/interview/",
      },
    },
  },
  "chncycling": {
    name: "中国自行车运动协会",
    column: "cycle-track",
    color: "blue",
    detail: true,
    home: "http://chncycling.org.cn/",
    sub: {
      "news": {
        title: "新闻动态",
        type: "affair",
        interval: Time.Common,
        home: "http://chncycling.org.cn/news/",
      },
      "bulletin-js": {
        title: "竞赛",
        type: "affair",
        interval: Time.Common,
        home: "http://chncycling.org.cn/bulletin/js/",
      },
      "bulletin-china": {
        title: "国家队",
        type: "affair",
        interval: Time.Common,
        home: "http://www.chncycling.org.cn/bulletin/china/",
      },
      "bulletin-xh": {
        title: "协会事务",
        type: "affair",
        interval: Time.Common,
        home: "http://www.chncycling.org.cn/bulletin/xh/",
      },
      "ss": {
        title: "自行车赛事",
        type: "affair",
        interval: Time.Common,
        home: "http://www.chncycling.org.cn/ss/",
      },
    },
  },
  "wildto": {
    name: "野途",
    column: "cycle-track",
    color: "green",
    detail: true,
    home: "https://www.wildto.com/",
    sub: {
      "news": {
        title: "赛事新闻",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.wildto.com/news/cycling/0",
      },
      "product": {
        title: "产品资讯",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.wildto.com/news/product/0/",
      },
      "industry-business": {
        title: "行业动态",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.wildto.com/news/industry/business/",
      },
      "industry-exhibition": {
        title: "展会聚焦",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.wildto.com/news/industry/exhibition/",
      },
      "bike-hotnews": {
        title: "热点资讯",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.wildto.com/news/bike/hotnews/",
      },
    },
  },
  "globalbikeinfo": {
    name: "全球自行车产业链信息网",
    column: "bike-industry",
    color: "emerald",
    detail: true,
    home: "https://www.globalbikeinfo.com/",
    sub: {
      news: {
        title: "业界资讯",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.globalbikeinfo.com/news",
      },
    },
  },
  "igpsport": {
    name: "迹驰",
    column: "competition",
    color: "blue",
    detail: true,
    home: "https://www.igpsport.cn/",
    sub: {
      news: {
        title: "最新资讯",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.igpsport.cn/blog",
      },
    },
  },
  "garmin": {
    name: "佳明",
    column: "competition",
    color: "blue",
    detail: true,
    home: "https://www.garmin.com/",
    sub: {
      bulletin: {
        title: "最新公告",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.garmin.com.cn/news/bulletin/",
      },
      news: {
        title: "最新资讯",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.garmin.com.cn/news/garmin/",
      },
    },
  },
  "imxingzhe": {
    name: "行者",
    column: "competition",
    color: "green",
    home: "https://www.imxingzhe.com/",
    sub: {
      news: {
        title: "推荐",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.imxingzhe.com/newsv2/list",
      },
    },
  },
  "huanqiu": {
    name: "环球网",
    column: "world",
    color: "red",
    detail: true,
    home: "https://www.huanqiu.com/",
    sub: {
      news: {
        title: "财经",
        type: "realtime",
        interval: Time.Common,
        home: "https://finance.huanqiu.com/",
      },
      tech: {
        title: "科技",
        type: "realtime",
        interval: Time.Common,
        home: "https://tech.huanqiu.com/",
      },
      capital: {
        title: "产业",
        type: "realtime",
        interval: Time.Common,
        home: "https://capital.huanqiu.com/",
      },
    },
  },
  "samr": {
    name: "国家市场监督管理局",
    column: "finance",
    color: "blue",
    detail: true,
    home: "https://www.samr.gov.cn/",
    sub: {
      xwfbt: {
        title: "新闻发布",
        type: "affair",
        interval: Time.Common,
        home: "https://www.samr.gov.cn/xw/xwfbt/index.html",
      },
      szyw: {
        title: "时政要闻",
        type: "affair",
        interval: Time.Common,
        home: "https://www.samr.gov.cn/xw/szyw/index.html",
      },
      tz: {
        title: "通知",
        type: "affair",
        interval: Time.Common,
        home: "https://www.samr.gov.cn/zw/zjwj/tz/index.html",
      },
      gsgg: {
        title: "公示公告",
        type: "affair",
        interval: Time.Common,
        home: "https://www.samr.gov.cn/zw/zjwj/gsgg/index.html",
      },
    },
  },
  "ceweekly": {
    name: "经济网",
    column: "finance",
    color: "red",
    detail: true,
    home: "https://www.ceweekly.cn/",
    sub: {
      news_important: {
        title: "热点观察",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.ceweekly.cn/news/important/",
      },
      macro: {
        title: "宏观经济",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.ceweekly.cn/finance/macro/",
      },
    },
  },
  "mof": {
    name: "财政部",
    column: "affair",
    color: "blue",
    detail: true,
    home: "http://www.mof.gov.cn/",
    sub: {
      czxw: {
        title: "财政新闻",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.mof.gov.cn/zhengwuxinxi/caizhengxinwen/",
      },
      zyzfmhwz: {
        title: "中央政府门户网站",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.mof.gov.cn/zhengwuxinxi/caijingshidian/zyzfmhwz/",
      },
      renminwang: {
        title: "人民日报",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.mof.gov.cn/zhengwuxinxi/caijingshidian/renminwang/",
      },
      xinhuanet: {
        title: "新华社",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.mof.gov.cn/zhengwuxinxi/caijingshidian/xinhuanet/",
      },
      jjrb: {
        title: "经济日报",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.mof.gov.cn/zhengwuxinxi/caijingshidian/jjrb/",
      },
      jjckb: {
        title: "经济参考报",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.mof.gov.cn/zhengwuxinxi/caijingshidian/jjckb/",
      },
      zgcjb: {
        title: "中国财经报",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.mof.gov.cn/zhengwuxinxi/caijingshidian/zgcjb/",
      },
      cjzylm: {
        title: "财经专用栏目",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.mof.gov.cn/zhengwuxinxi/caijingshidian/cjzylm/",
      },
    },
  },
  "stascn": {
    name: "国家统计局",
    column: "affair",
    color: "blue",
    detail: true,
    home: "https://www.stats.gov.cn/",
    sub: {
      tjdt: {
        title: "统计动态",
        type: "affair",
        interval: Time.Common,
        home: "https://www.stats.gov.cn/xw/tjxw/tjdt/",
      },
      tzgg: {
        title: "通知公告",
        type: "affair",
        interval: Time.Common,
        home: "https://www.stats.gov.cn/xw/tjxw/tzgg/",
      },
    },
  },
  "wahooprice": {
    name: "WAHOO",
    title: "最新价格",
    column: "competition",
    color: "blue",
    type: "realtime",
    interval: Time.Common,
    home: "https://www.wahoofitness.com/",
  },
  "garminprice": {
    name: "Garmin",
    title: "最新价格",
    column: "competition",
    color: "blue",
    type: "realtime",
    interval: Time.Common,
    home: "https://www.garmin.com/",
  },
  "decathlonprice": {
    name: "Decathlon",
    title: "最新价格",
    column: "competition",
    color: "blue",
    type: "realtime",
    interval: Time.Common,
    home: "https://www.decathlon.fr/",
  },
  "jetblackcycling": {
    name: "JetBlack",
    title: "最新价格",
    column: "competition",
    color: "blue",
    type: "realtime",
    interval: Time.Common,
    home: "https://www.jetblackcycling.com/",
  },
  "wahoo": {
    name: "WAHOO",
    column: "competition",
    color: "blue",
    home: "https://www.wahoofitness.com/",
    sub: {
      banner: {
        title: "首页 Banner",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.wahoofitness.com/",
      },
    },
  },
  "shimano": {
    name: "shimano-EN",
    column: "competition",
    color: "blue",
    home: "https://www.shimano.com/en/",
    sub: {
      banner: {
        title: "首页 Banner",
        type: "realtime",
        interval: Time.Common,
        home: "https://bike.shimano.com/en-NA/home.html",
      },
    },
  },
  "sram": {
    name: "SRAM-EN",
    column: "competition",
    color: "blue",
    home: "https://www.sram.com/en/sram",
    sub: {
      shop: {
        title: "Shop Banner",
        type: "realtime",
        interval: Time.Common,
        home: "https://shop.sram.com/",
      },
    },
  },
  "favero": {
    name: "Favero-EN",
    column: "competition",
    color: "blue",
    home: "https://cycling.favero.com/",
    sub: {
      shop: {
        title: "Shop Goods",
        type: "realtime",
        interval: Time.Common,
        home: "https://cycling.favero.com/shop/",
      },
    },
  },
  "igpsport-USA": {
    name: "迹驰",
    column: "competition",
    color: "blue",
    icon: "public/icons/igpsport.png",
    home: "https://www.igpsport.com/",
    sub: {
      banner: {
        title: "首页 Banner",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.igpsport.com/",
      },
    },
  },
  "cycplus": {
    name: "CYCPLUS",
    column: "competition",
    color: "blue",
    home: "https://www.cycplus.com/",
    sub: {
      banner: {
        title: "首页 Banner",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.cycplus.com/",
      },
    },
  },
  "elite": {
    name: "Elite",
    column: "competition",
    color: "blue",
    home: "https://www.elite-it.com/en",
    sub: {
      banner: {
        title: "首页 Banner",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.elite-it.com/en",
      },
    },
  },
  "cybrei": {
    name: "CYBREI",
    column: "competition",
    color: "blue",
    home: "https://www.cybrei.com/",
    sub: {
      banner: {
        title: "首页 Banner",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.cybrei.com/",
      },
    },
  },
  "xcadey": {
    name: "XCADEY",
    column: "competition",
    color: "blue",
    home: "https://www.xcadey.com/",
    sub: {
      banner: {
        title: "首页 Banner",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.xcadey.com/",
      },
    },
  },
  "bryton": {
    name: "Bryton",
    column: "competition",
    color: "blue",
    home: "https://www.brytonsport.com/",
    sub: {
      banner: {
        title: "首页 Banner",
        type: "realtime",
        interval: Time.Common,
        home: "https://global.brytonsport.com/",
      },
    },
  },
  "lezyne": {
    name: "Lezyne",
    column: "competition",
    color: "blue",
    home: "https://www.lezyne.com/",
    sub: {
      banner: {
        title: "首页 Banner",
        type: "realtime",
        interval: Time.Common,
        home: "https://ride.lezyne.com/",
      },
    },
  },
  "thinkrider": {
    name: "ThinkRider",
    column: "competition",
    color: "blue",
    home: "https://www.thinkrider.com/",
    sub: {
      banner: {
        title: "首页 Banner",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.thinkrider.com/",
      },
    },
  },
  "power2max": {
    name: "Power2Max",
    column: "competition",
    color: "blue",
    home: "https://www.power2max.com/en/",
    sub: {
      banner: {
        title: "首页 Banner",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.power2max.com/en/",
      },
    },
  },
  "cyclingnews": {
    name: "CyclingNews",
    column: "cycle-track",
    color: "blue",
    detail: true,
    home: "https://www.cyclingnews.com",
    sub: {
      news: {
        title: "新闻资讯",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.cyclingnews.com/news/",
      },
    },
  },
  "roadcc": {
    name: "road.cc",
    column: "cycle-track",
    color: "blue",
    detail: true,
    home: "https://road.cc",
    sub: {
      news: {
        title: "新闻资讯",
        type: "realtime",
        interval: Time.Common,
        home: "https://road.cc/news",
      },
    },
  },
  "bikeradar": {
    name: "BikeRadar",
    column: "cycle-track",
    color: "blue",
    detail: true,
    home: "https://www.bikeradar.com",
    sub: {
      news: {
        title: "新闻资讯",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.bikeradar.com/news",
      },
    },
  },
  "cyclingchina": {
    name: "骑行家",
    column: "cycle-track",
    color: "blue",
    detail: true,
    home: "http://www.cyclingchina.net",
    sub: {
      "news": {
        title: "行业新闻",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.cyclingchina.net/site/html/news/",
      },
      "events": {
        title: "赛事活动",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.cyclingchina.net/site/html/events/",
      },
      "new-product": {
        title: "新产品",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.cyclingchina.net/site/html/new_product/",
      },
      "must-know": {
        title: "骑行必知",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.cyclingchina.net/site/html/must_know/",
      },
    },
  },
  "dcrainmaker": {
    name: "DC Rainmaker",
    column: "cycle-track",
    color: "blue",
    detail: true,
    home: "https://www.dcrainmaker.com/",
    sub: {
      blog: {
        title: "最新资讯",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.dcrainmaker.com/blog/",
      },
    },
  },
  "qdstc": {
    name: "青岛市科学技术局",
    column: "affair",
    color: "blue",
    detail: true,
    home: "http://qdstc.qingdao.gov.cn/",
    sub: {
      tzgg: {
        title: "通知公告",
        type: "realtime",
        interval: Time.Common,
        home: "http://qdstc.qingdao.gov.cn/kjdt/tzgg/",
      },
    },
  },
  "qdzct": {
    name: "青岛政策通",
    column: "affair",
    color: "blue",
    detail: true,
    home: "https://zccx.qingdao.gov.cn/",
    sub: {
      zcsx: {
        title: "政策事项",
        type: "realtime",
        interval: Time.Common,
        home: "https://zccx.qingdao.gov.cn/policy/itemList.html",
      },
    },
  },
  "gxj": {
    name: "青岛市工业和信息化局",
    column: "affair",
    color: "blue",
    detail: true,
    home: "http://gxj.qingdao.gov.cn/",
    sub: {
      tzgg: {
        title: "通知公告",
        type: "realtime",
        interval: Time.Common,
        home: "http://gxj.qingdao.gov.cn/tzgg/",
      },
    },
  },
  "hrss": {
    name: "青岛市人力资源和社会保障局",
    column: "affair",
    color: "blue",
    detail: true,
    home: "https://hrss.qingdao.gov.cn/",
    sub: {
      tzgg: {
        title: "通知公告",
        type: "realtime",
        interval: Time.Common,
        home: "https://hrss.qingdao.gov.cn/zxzx_47/tzgg_47/",
      },
    },
  },
  "kjt": {
    name: "山东省科技云服务平台",
    column: "affair",
    color: "blue",
    detail: true,
    home: "https://cloud.kjt.shandong.gov.cn/",
    sub: {
      tzgg: {
        title: "通知公告",
        type: "realtime",
        interval: Time.Common,
        home: "https://cloud.kjt.shandong.gov.cn/newportal/channels/ch00018/",
      },
    },
  },
  "sdkjt": {
    name: "山东省科学技术厅",
    column: "affair",
    color: "blue",
    detail: true,
    home: "http://kjt.shandong.gov.cn/",
    sub: {
      tzgg: {
        title: "通知公告",
        type: "realtime",
        interval: Time.Common,
        home: "http://kjt.shandong.gov.cn/col/col13360/index.html",
      },
    },
  },
  "sdgxt": {
    name: "山东省工业和信息化厅",
    column: "affair",
    color: "blue",
    detail: true,
    home: "http://gxt.shandong.gov.cn/",
    sub: {
      tz: {
        title: "政务公开-通知",
        type: "realtime",
        interval: Time.Common,
        home: "http://gxt.shandong.gov.cn/col/col15201/index.html",
      },
      gg: {
        title: "政务公开-公告",
        type: "realtime",
        interval: Time.Common,
        home: "http://gxt.shandong.gov.cn/col/col15202/index.html",
      },
      gs: {
        title: "政务公开-公示",
        type: "realtime",
        interval: Time.Common,
        home: "http://gxt.shandong.gov.cn/col/col15203/index.html",
      },
    },
  },
  "sdty": {
    name: "山东省体育局",
    column: "affair",
    color: "blue",
    detail: true,
    home: "http://ty.shandong.gov.cn/",
    sub: {
      tzgga: {
        title: "通知公告",
        type: "realtime",
        interval: Time.Common,
        home: "http://ty.shandong.gov.cn/zwgk/tzgga/",
      },
    },
  },
  "myj": {
    name: "青岛市民营经济发展局",
    column: "affair",
    color: "blue",
    detail: true,
    home: "http://myj.qingdao.gov.cn/",
    sub: {
      tzgg: {
        title: "通知公告",
        type: "realtime",
        interval: Time.Common,
        home: "http://myj.qingdao.gov.cn/tzgg/",
      },
    },
  },
  "dpc": {
    name: "青岛市发展和改革委员会",
    column: "affair",
    color: "blue",
    detail: true,
    home: "http://dpc.qingdao.gov.cn/",
    sub: {
      tzgg: {
        title: "政策公告",
        type: "realtime",
        interval: Time.Common,
        home: "http://dpc.qingdao.gov.cn/tzgg_45/list.shtml",
      },
    },
  },
  "sdhrss": {
    name: "山东省人力资源和社会保障厅",
    column: "affair",
    color: "blue",
    detail: true,
    home: "https://hrss.shandong.gov.cn/",
    sub: {
      tzgg: {
        title: "通知公告",
        type: "realtime",
        interval: Time.Common,
        home: "https://hrss.shandong.gov.cn/channels/ch00330/",
      },
    },
  },
  "fgw": {
    name: "山东省发展和改革委员会",
    column: "affair",
    color: "blue",
    detail: true,
    home: "http://fgw.shandong.gov.cn/",
    sub: {
      tzgg: {
        title: "通知公告",
        type: "realtime",
        interval: Time.Common,
        home: "http://fgw.shandong.gov.cn/col/col91082/index.html",
      },
    },
  },
  "miit": {
    name: "工业和信息化部",
    column: "affair",
    color: "blue",
    detail: true,
    home: "https://www.miit.gov.cn/",
    sub: {
      wjfb: {
        title: "政策文件库-文件发布",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.miit.gov.cn/search/zcwjk.html?category=183",
      },
      zxzc: {
        title: "最新政策",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.miit.gov.cn/xwfb/zxzc/index.html",
      },
    },
  },
  "govpolicy": {
    name: "国务院政策文件库",
    title: "最新政策",
    type: "realtime",
    column: "affair",
    color: "red",
    robots: "ignore",
    interval: Time.Common,
    home: "https://sousuo.www.gov.cn/zcwjk/policyDocumentLibrary?q=&t=zhengcelibrary&orpro=",
  },
  "ndrc": {
    name: "国家发改委",
    column: "affair",
    color: "blue",
    detail: true,
    home: "https://www.ndrc.gov.cn/",
    sub: {
      tzgg: {
        title: "通知公告",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.ndrc.gov.cn/xwdt/tzgg/",
      },
    },
  },
  "amr": {
    name: "青岛市市场监督管理局",
    column: "affair",
    color: "blue",
    detail: true,
    home: "https://amr.qingdao.gov.cn/",
    sub: {
      tzgg: {
        title: "通知公告",
        type: "realtime",
        interval: Time.Common,
        home: "https://amr.qingdao.gov.cn/zwgk/tzgg/",
      },
    },
  },
  "qdtyj": {
    name: "青岛市体育局",
    column: "affair",
    color: "blue",
    detail: true,
    home: "http://tiyuju.qingdao.gov.cn/",
    sub: {
      tzgg: {
        title: "通知公告",
        type: "realtime",
        interval: Time.Common,
        home: "http://tiyuju.qingdao.gov.cn/tzgg/",
      },
    },
  },
  "bofcom": {
    name: "青岛市商务局",
    column: "affair",
    color: "blue",
    detail: true,
    home: "http://bofcom.qingdao.gov.cn/",
    sub: {
      zytz: {
        title: "重要通知",
        type: "realtime",
        interval: Time.Common,
        home: "http://bofcom.qingdao.gov.cn/zwgk_59/zytz_59/",
      },
      zcfb: {
        title: "政策发布",
        type: "realtime",
        interval: Time.Common,
        home: "http://bofcom.qingdao.gov.cn/zwgk_59/zcfb_59/",
      },
    },
  },
  "sport": {
    name: "国家体育总局",
    column: "affair",
    color: "blue",
    detail: true,
    home: "https://www.sport.gov.cn/",
    sub: {
      tzgg: {
        title: "通知公告",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.sport.gov.cn/n315/n20001395/index.html",
      },
    },
  },
  "chinadesign": {
    name: "中国工业设计协会",
    column: "affair",
    color: "blue",
    detail: true,
    home: "https://www.chinadesign.cn/",
    sub: {
      news: {
        title: "通知公告",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.chinadesign.cn/15/index.html",
      },
    },
  },
  "chinabicycle": {
    name: "中国自行车协会",
    column: "affair",
    color: "blue",
    detail: true,
    home: "http://www.china-bicycle.com/",
    sub: {
      js: {
        title: "技术",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.china-bicycle.com/news/index/30?cid=15",
      },
      bz: {
        title: "标准",
        type: "realtime",
        interval: Time.Common,
        home: "http://www.china-bicycle.com/news/index/31?cid=16",
      },
      zcfg: {
        title: "政策法规",
        type: "realtime",
        column: "industry",
        interval: Time.Common,
        home: "https://www.china-bicycle.com/news/index/41?cid=51",
      },
      xgb: {
        title: "新国标实施",
        type: "realtime",
        column: "industry",
        interval: Time.Common,
        home: "https://www.china-bicycle.com/news/index/47/?cid=58",
      },
      wh: {
        title: "自行车文化",
        type: "realtime",
        column: "industry",
        interval: Time.Common,
        home: "https://www.china-bicycle.com/news/index/33?cid=3",
      },
      tz: {
        title: "重要通知",
        type: "realtime",
        column: "industry",
        interval: Time.Common,
        home: "https://www.china-bicycle.com/news/index/1?cid=12",
      },
      imp: {
        title: "重要新闻",
        type: "realtime",
        column: "industry",
        interval: Time.Common,
        home: "https://www.china-bicycle.com/news/important?cid=2",
      },
      zg: {
        title: "中国展",
        type: "realtime",
        column: "industry",
        interval: Time.Common,
        home: "https://www.china-bicycle.com/news/index/24?cid=18",
      },
      dfz: {
        title: "地方展",
        type: "realtime",
        column: "industry",
        interval: Time.Common,
        home: "https://www.china-bicycle.com/news/index/25?cid=19",
      },
    },
  },
  "peopleforbikes": {
    name: "PeopleForBikes",
    column: "industry",
    color: "blue",
    home: "https://www.peopleforbikes.org/",
    sub: {
      news: {
        title: "News",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.peopleforbikes.org/news",
      },
      business: {
        title: "Bike Business",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.peopleforbikes.org/topics/bike-business",
      },
      research: {
        title: "Research",
        type: "realtime",
        interval: Time.Slow,
        home: "https://www.peopleforbikes.org/research",
      },
    },
  },
  "federciclismo": {
    name: "Federciclismo",
    desc: "意大利自行车联合会 FCI",
    type: "realtime",
    column: "industry",
    color: "green",
    interval: Time.Common,
    home: "https://www.federciclismo.it/",
  },
  "colombiaciclismo": {
    name: "FECOCI",
    desc: "哥伦比亚自行车联合会",
    type: "realtime",
    column: "industry",
    color: "yellow",
    interval: Time.Common,
    home: "https://federacioncolombianadeciclismo.com/",
  },
  "ziv": {
    name: "ZIV",
    desc: "德国两轮车工业协会",
    type: "realtime",
    column: "industry",
    color: "amber",
    interval: Time.Common,
    home: "https://www.ziv-zweirad.de/",
  },
  "cyclingorgtw": {
    name: "中华台北自由车协会",
    desc: "Chinese Taipei Cycling Association",
    type: "realtime",
    column: "industry",
    color: "teal",
    interval: Time.Common,
    home: "https://cycling.org.tw/",
  },
  "conade": {
    name: "CONADE",
    desc: "墨西哥国家体育委员会",
    type: "realtime",
    column: "industry",
    color: "red",
    interval: Time.Slow,
    home: "https://www.gob.mx/conade",
  },
  "britishcycling": {
    name: "British Cycling",
    desc: "英国自行车协会",
    type: "realtime",
    column: "industry",
    color: "blue",
    interval: Time.Common,
    home: "https://www.britishcycling.org.uk",
  },
  "pzkol": {
    name: "PZKol",
    desc: "波兰自行车协会",
    type: "realtime",
    column: "industry",
    color: "red",
    interval: Time.Common,
    home: "https://www.pzkol.pl/",
  },
  "mncf": {
    name: "MNCF",
    desc: "马来西亚自行车联合会",
    type: "realtime",
    column: "industry",
    color: "orange",
    interval: Time.Slow,
    home: "https://www.mncf.my/",
  },
  "cbc": {
    name: "CBC",
    desc: "巴西自行车联合会",
    type: "realtime",
    column: "industry",
    color: "green",
    interval: Time.Common,
    home: "https://www.cbc.esp.br/",
  },
  "bikeretailer": {
    name: "Bicycle Retailer",
    desc: "BRAIN 北美自行车行业媒体",
    type: "realtime",
    column: "industry",
    color: "indigo",
    home: "https://www.bicycleretailer.com",
    sub: {
      industry: {
        title: "Industry News",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.bicycleretailer.com/industry-news",
      },
      announcements: {
        title: "Announcements",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.bicycleretailer.com/announcements",
      },
      opinion: {
        title: "Opinion & Analysis",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.bicycleretailer.com/opinion-analysis",
      },
      products: {
        title: "New Products",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.bicycleretailer.com/new-products",
      },
    },
  },
  "cyclingindustry": {
    name: "CyclingIndustry.News",
    desc: "英国自行车行业媒体",
    type: "realtime",
    column: "industry",
    color: "orange",
    home: "https://cyclingindustry.news/",
    sub: {
      news: {
        title: "News",
        type: "realtime",
        interval: Time.Common,
        home: "https://cyclingindustry.news/niche/news-50-968/",
      },
      investment: {
        title: "Investment & Acquisitions",
        type: "realtime",
        interval: Time.Common,
        home: "https://cyclingindustry.news/niche/investment-acquisitions/",
      },
    },
  },
  "ancma": {
    name: "ANCMA",
    column: "industry",
    color: "red",
    home: "https://www.ancma.it/",
    sub: {
      news: {
        title: "Association News",
        type: "realtime",
        interval: Time.Common,
        home: "https://ancma.news/?jsf=jet-engine:grid1&tax=category:342",
      },
      associates: {
        title: "Associati News",
        type: "realtime",
        interval: Time.Common,
        home: "https://ancma.news/category/news/notizie-dagli-associati/",
      },
      statistics: {
        title: "Statistics",
        type: "realtime",
        interval: Time.Slow,
        home: "https://www.ancma.it/statistiche/",
      },
    },
  },
  "fvsr": {
    name: "ФВСР",
    column: "industry",
    color: "blue",
    home: "https://fvsr.ru/",
    sub: {
      news: {
        title: "Новости",
        type: "realtime",
        interval: Time.Common,
        home: "https://fvsr.ru/press/news",
      },
      highway: {
        title: "Шоссе",
        type: "realtime",
        interval: Time.Common,
        home: "https://fvsr.ru/press/news?tag=highway",
      },
      track: {
        title: "Трек",
        type: "realtime",
        interval: Time.Common,
        home: "https://fvsr.ru/press/news?tag=track",
      },
      documents: {
        title: "Документы",
        type: "realtime",
        interval: Time.Slow,
        home: "https://fvsr.ru/documents",
      },
    },
  },
  "czechcycling": {
    name: "Český svaz cyklistiky",
    column: "industry",
    color: "red",
    home: "https://www.czechcyclingfederation.com/",
    sub: {
      novinky: {
        title: "Novinky",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.czechcyclingfederation.com/category/novinky/",
      },
      documents: {
        title: "Dokumenty",
        type: "realtime",
        interval: Time.Slow,
        home: "https://www.czechcyclingfederation.com/svaz/dokumenty/",
      },
    },
  },
  "auscycling": {
    name: "AusCycling",
    column: "industry",
    color: "green",
    home: "https://auscycling.org.au/",
    sub: {
      news: {
        title: "News",
        type: "realtime",
        interval: Time.Common,
        home: "https://auscycling.org.au/news",
      },
      policies: {
        title: "Policies",
        type: "realtime",
        interval: Time.Slow,
        home: "https://auscycling.org.au/about/policies",
      },
      annualreport: {
        title: "Annual Reports",
        type: "realtime",
        interval: Time.Slow,
        home: "https://auscycling.org.au/about/annual-report",
      },
      governance: {
        title: "Governance",
        type: "realtime",
        interval: Time.Slow,
        home: "https://auscycling.org.au/about/governance",
      },
      strategy: {
        title: "Strategy",
        type: "realtime",
        interval: Time.Slow,
        home: "https://auscycling.org.au/about/strategy",
      },
    },
  },
  "ffc": {
    name: "Fédération Française de Cyclisme",
    column: "industry",
    color: "blue",
    home: "https://ffc.fr/",
    sub: {
      structures: {
        title: "Structures News",
        type: "realtime",
        interval: Time.Common,
        home: "https://structures.ffc.fr/nos-actualites/",
      },
      velo: {
        title: "France à vélo",
        type: "realtime",
        interval: Time.Common,
        home: "https://velo.ffc.fr/actualites/",
      },
      resources: {
        title: "Ressources",
        type: "realtime",
        interval: Time.Common,
        home: "https://ffc.fr/ressources/",
      },
    },
  },
  "jbpi": {
    name: "自転車産業振興協会",
    column: "industry",
    color: "blue",
    home: "https://jbpi.or.jp/",
    sub: {
      business: {
        title: "各種事業最新情報",
        type: "realtime",
        interval: Time.Common,
        home: "https://jbpi.or.jp/business-list/",
      },
    },
  },
  "singaporecycling": {
    name: "Singapore Cycling Federation",
    column: "industry",
    color: "red",
    home: "https://singaporecycling.org.sg/",
    sub: {
      news: {
        title: "News",
        type: "realtime",
        interval: Time.Common,
        home: "https://singaporecycling.org.sg/blogs/news",
      },
      policies: {
        title: "Event Policies & Guidelines",
        type: "realtime",
        interval: Time.Slow,
        home: "https://singaporecycling.org.sg/pages/event-policies-guidelines",
      },
    },
  },
  "cyclingcanada": {
    name: "Cycling Canada",
    column: "industry",
    color: "red",
    home: "https://cyclingcanada.ca/",
    sub: {
      general: {
        title: "General News",
        type: "realtime",
        interval: Time.Common,
        home: "https://cyclingcanada.ca/sport/general/",
      },
      rules: {
        title: "Rules & Policies",
        type: "realtime",
        interval: Time.Slow,
        home: "https://cyclingcanada.ca/get-involved/officials/rules-policies/",
      },
    },
  },
  "cyclingchile": {
    name: "Federación Deportiva Nacional de Ciclismo de Chile",
    column: "industry",
    color: "red",
    home: "https://fdnciclismochile.cl/",
    sub: {
      noticias: {
        title: "Noticias",
        type: "realtime",
        interval: Time.Common,
        home: "https://fdnciclismochile.cl/blogs/noticias",
      },
      documents: {
        title: "Documentos",
        type: "realtime",
        interval: Time.Slow,
        home: "https://fdnciclismochile.cl/pages/documentos-1",
      },
    },
  },
  "ldsf": {
    name: "Lietuvos dviračių sporto federacija",
    column: "industry",
    color: "green",
    home: "https://ldsf.lt/",
    sub: {
      news: {
        title: "Naujienos",
        type: "realtime",
        interval: Time.Common,
        home: "https://ldsf.lt/naujienos/",
      },
      reports: {
        title: "Ataskaitos",
        type: "realtime",
        interval: Time.Slow,
        home: "https://ldsf.lt/dokumentai/ataskaitos/",
      },
    },
  },
  "uci": {
    name: "UCI",
    column: "industry",
    color: "blue",
    home: "https://www.uci.org/",
    sub: {
      news: {
        title: "News",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.uci.org/news/all-news/6IQ886FTfWV8yd13Egt9v3",
      },
      regulations: {
        title: "Regulations",
        type: "realtime",
        interval: Time.Slow,
        home: "https://www.uci.org/regulations/3MyLDDrwJCJJ0BGGOFzOat",
      },
    },
  },
  "bikeeu": {
    name: "Bike Europe",
    column: "industry",
    color: "blue",
    home: "https://www.bike-eu.com/",
    sub: {
      news: {
        title: "News",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.bike-eu.com/news",
      },
      product: {
        title: "Product Regulations",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.bike-eu.com/collecties/product",
      },
      trade: {
        title: "Trade Regulations",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.bike-eu.com/collecties/trade",
      },
    },
  },
  "cyclingindustries": {
    name: "European Cycling Industries",
    column: "industry",
    color: "blue",
    home: "https://cyclingindustries.com/",
    sub: {
      news: {
        title: "News",
        type: "realtime",
        interval: Time.Common,
        home: "https://cyclingindustries.com/news/",
      },
      market: {
        title: "Market Impact & Intelligence",
        type: "realtime",
        interval: Time.Common,
        home: "https://cyclingindustries.com/news/details/category/market-impact-and-intelligence/",
      },
    },
  },
  "csgf": {
    name: "中国体育用品业联合会",
    column: "affair",
    color: "blue",
    detail: true,
    home: "https://cn.csgf.org.cn/",
    sub: {
      xhgg: {
        title: "协会公告",
        type: "realtime",
        interval: Time.Common,
        home: "https://cn.csgf.org.cn/xhxx/xhgg/list_1.html",
      },
    },
  },
  "csia": {
    name: "中国软件行业协会",
    column: "affair",
    color: "blue",
    detail: true,
    home: "https://www.csia.org.cn/",
    sub: {
      tzgg: {
        title: "通知公告",
        type: "realtime",
        interval: Time.Common,
        home: "https://www.csia.org.cn/front/branch/10",
      },
    },
  },
} as const satisfies Record<string, OriginSource>

export function genSources() {
  const _: [SourceID, Source][] = []

  Object.entries(originSources).forEach(([id, source]: [any, OriginSource]) => {
    const parent = {
      name: source.name,
      type: source.type,
      detail: source.detail,
      robots: source.robots,
      disable: source.disable,
      desc: source.desc,
      icon: source.icon,
      column: source.column,
      home: source.home,
      color: source.color ?? "primary",
      interval: source.interval ?? Time.Default,
    }
    if (source.sub && Object.keys(source.sub).length) {
      Object.entries(source.sub).forEach(([subId, subSource], i) => {
        if (i === 0) {
          _.push([
            id,
            {
              redirect: `${id}-${subId}`,
              ...parent,
              ...subSource,
            },
          ] as [any, Source])
        }
        _.push([`${id}-${subId}`, { ...parent, ...subSource }] as [
          any,
          Source,
        ])
      })
    } else {
      _.push([
        id,
        {
          title: source.title,
          ...parent,
        },
      ])
    }
  })

  return typeSafeObjectFromEntries(
    _.filter(([_, v]) => {
      if (v.disable === "cf" && process.env.CF_PAGES) {
        return false
      } else {
        return v.disable !== true
      }
    }),
  )
}
